::: {.content-hidden}
Copyright (C) 2024-2025 Harald Pretl and co-authors (harald.pretl@jku.at)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
:::

# Inverter-Based OTA {#sec-inverter-based-ota}

Book:

- Bram Nauta - Analog CMOS Filters for Very High Frequencies

Papers:

- Bram Nauta - A CMOS Transconductance-C Filter Technique for Very High Frequencies: https://ris.utwente.nl/ws/files/6771395/cmos_transconductance.pdf

- Luís Henrique Rodovalho et al. - Hybrid Inverter-Based Fully Differential Operational Transconductance Amplifiers: https://www.mdpi.com/2674-0729/2/1/1

- Herve Barthelemy et al. - OTA based on CMOS inverters and application in the design of tunable bandpass filter: https://link.springer.com/article/10.1007/s10470-008-9167-8

- Giuseppe Manfredini - Ultra-Low-Voltage Inverter-Based Amplifier with Novel Common-Mode Stabilization Loop: https://www.mdpi.com/2079-9292/9/6/1019

Content:

- Explain Inverter-Based OTAs (Advantages / Disadvantages)

- Overview of Inverter-Based OTA Topologies

- Show Design Equations

- Design Inverter-Based OTA

- Simulation in Xschem

- Show reference layout