::: {.content-hidden}
Copyright (C) 2024-2025 Harald Pretl and co-authors (harald.pretl@jku.at)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
:::

# Active Filters {#sec-active-filters}

- Why active filters?
- Advantages / Disadvantages (no L, but not suited for RF, etc.)

Books:
- Lutz Wangenheim - Aktive Filter und Oszillatoren
- Ulrich Tietze, Christoph Schenk, Eberhard Gamm - Halbleiter-Schaltungstechnik
- Kendall Su - Analog Filters

## Basics
- Show Plot with lowpass, highpass, bandpass and notch filters (Abb. 12.1 Tietze / Schenk) and biquad transfer function (see ANAS Timm)
- Toleranzschema (see ANAS Timm)
- Description in the frequency domain (transfer function, magnitude, phase, poles, zeros)
- default and low-entropy transfer function

## Filter Approximations
- Critical Damping
- Butterworth
- Bessel
- Chebychev
- Inverse Chebychev
- Cauer / Elliptic
- Compare these filters: Advantages / Disadvantage
- Magnitude response, Gruppenlaufzeit, Sprungantwort und Pole in S-Ebene für 4. Ordnung und 10. Ordnung (see Tietze Schenk)
- Herleitung von Polynome --> Verweis auf Tietze Schenk
- Anschreiben von Bessel und Butterworth Polynome
- Filterkoeffizienten Tabellen 

## Filter Transformations
- Lowpass-Highpass transformation
- Lowpass-Bandpass transformation

## Filter Topologies
- Sallen-Key (SK) Filter
- Multiple-Feedback (MFB) Filter
- Tow-Thomas (TT) Filter
- GIC Filter
- Akerberg-Moosberg Filter
- Twin-T Notch Filter
- Compare these filters: Advantages / Disadvantage

## Design of 2nd-order MFB Lowpass Filter
- Behzad Razavi - The Design of a Biquadratic Filter [The Analog Mind]: https://ieeexplore.ieee.org/document/10410055
- Behzad Razavi - The Biquadratic Filter [A Circuit for All Seasons]: https://ieeexplore.ieee.org/document/8390964
- derive RC transfer function
- Koeffizientenvergleich with transfer function of 2nd order lowpass
- derive equations (for biquads, these formulas exist)
- calculate RC
- simulate filter in Xschem with 5T-OTA (single-ended)
- extend to fully-differential version (use inverter-based OTA above)

explain that this cookbook can be used for any other filter type as well. the well-known filters have equations --> just look into the table and plug in the coeficients.

## Higher-Order Active Filters
- This filter can also be extended to a 3rd-order MFB with only one OTA --> see Simon Paper

- Cascading biquads and using coefficients tables

## Design of 4th-order MFB Lowpass Filter
ToDo